version: "3.9"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /project
  nginx:
    image: "nginx:1.29.0-alpine"
    volumes:
      - type: bind
        source: ./
        target: /project
      - type: bind
        source: ./docker/nginx/default.conf.template
        target: /etc/nginx/templates/default.conf.template
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    links:
      - php
  db:
    image: postgres:17.5-alpine3.22
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - type: bind
        source: ./
        target: /project